import { test, expect, type Page } from '@playwright/test';
const openSettings = async (page: Page) => { await page.getByRole('button', { name: '账号菜单', exact: true }).click(); await page.getByRole('menuitem', { name: '设置', exact: true }).click(); await expect(page.getByRole('dialog', { name: '设置', exact: true })).toBeVisible(); };
test.beforeEach(async ({ page }) => {
    const headers = { 'x-workbench-client': 'test' };
    expect((await page.request.post('/api/login', { headers, data: { username: 'settings-user', password: 'e2e-password-123' } })).ok()).toBe(true);
    const identity = await (await page.request.get('/api/identity')).json();
    await page.request.post('/api/account/preferences', { headers, data: { theme: 'light', language: 'zh-CN', version: identity.preferences.version } });
    await page.goto('/');
    await expect(page.locator('.ProseMirror').first()).toBeVisible();
});
test('账号条只有一个入口，菜单不重复身份，关闭后焦点返回', async ({ page }) => {
    await expect(page.getByRole('button', { name: '设置与 Agent 接入', exact: true })).toHaveCount(0);
    const bar = page.getByRole('button', { name: '账号菜单', exact: true });
    await bar.click(); const menu = page.getByRole('menu', { name: '账号操作' });
    await expect(menu.getByText('settings-user', { exact: true })).toHaveCount(0);
    await expect(menu.getByText('当前账号')).toHaveCount(0);
    await expect(menu.getByRole('menuitem')).toHaveCount(2);
    await page.keyboard.press('Escape'); await expect(menu).toHaveCount(0); await expect(bar).toBeFocused();
    await page.keyboard.press('Enter'); await page.keyboard.press('Enter');
    await expect(page.getByRole('dialog', { name: '设置', exact: true })).toBeVisible();
    await expect(page.getByRole('tab', { name: '账号与安全', exact: true })).toBeVisible();
    await page.keyboard.press('Escape'); await expect(bar).toBeFocused();
});
test('浮窗不替换正文，分页保留表单，关闭未提交输入需要确认', async ({ page }) => {
    await page.locator('.ProseMirror').first().evaluate(element => element.setAttribute('data-settings-test', 'preserved'));
    await openSettings(page); const dialog = page.getByRole('dialog', { name: '设置', exact: true });
    await dialog.getByLabel('当前密码', { exact: true }).fill('unsubmitted-password');
    await dialog.getByRole('tab', { name: '通用', exact: true }).click();
    await dialog.getByRole('tab', { name: '账号与安全', exact: true }).click();
    await expect(dialog.getByLabel('当前密码', { exact: true })).toHaveValue('unsubmitted-password');
    await dialog.getByRole('button', { name: '关闭', exact: true }).click();
    const confirmation = page.getByRole('dialog', { name: '关闭设置？', exact: true });
    await expect(confirmation).toBeVisible(); await page.keyboard.press('Escape');
    await expect(confirmation).toHaveCount(0); await expect(dialog).toBeVisible();
    await dialog.getByRole('button', { name: '关闭', exact: true }).click();
    await confirmation.getByRole('button', { name: '放弃并关闭' }).click();
    await expect(dialog).toHaveCount(0); await expect(page.locator('.ProseMirror').first()).toHaveAttribute('data-settings-test', 'preserved');
});
test('主题与语言贯穿编辑界面，刷新保留偏好且正文和版本不变', async ({ page }) => {
    const before = await (await page.request.get('/api/workspace')).json();
    const documentText = () => page.locator('.ProseMirror').first().evaluate(element => { const clone = element.cloneNode(true) as HTMLElement; clone.querySelectorAll('[role=region]').forEach(region => region.remove()); return clone.textContent; });
    const body = await documentText();
    await openSettings(page); await page.getByRole('tab', { name: '通用', exact: true }).click();
    await page.screenshot({ path: '.local-data/settings-light.png', fullPage: true });
    await page.getByRole('radio', { name: '深色', exact: true }).click();
    await expect(page.getByRole('radio', { name: '深色', exact: true })).toBeChecked();
    await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark');
    await page.getByLabel('界面语言', { exact: true }).selectOption('en');
    await expect(page.getByRole('tab', { name: 'General', exact: true })).toBeVisible();
    await expect(page.getByRole('dialog', { name: 'Settings', exact: true })).toBeVisible();
    expect(await documentText()).toBe(body);
    await page.screenshot({ path: '.local-data/settings-dark.png', fullPage: true });
    await page.getByRole('button', { name: 'Close', exact: true }).click();
    await expect(page.getByRole('button', { name: 'Publish changes', exact: true })).toBeVisible();
    await expect(page.getByText('My drafts', { exact: true }).first()).toBeVisible();
    await page.reload(); await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark');
    await expect(page.getByRole('button', { name: 'Account menu', exact: true })).toBeVisible();
    const after = await (await page.request.get('/api/workspace')).json();
    expect(after.tree).toEqual(before.tree); expect(after.workspace).toEqual(before.workspace); expect(after.main).toBe(before.main);
});
test('系统主题可随设备变化，窄屏菜单与浮窗不横向溢出', async ({ page }) => {
    await page.setViewportSize({ width: 390, height: 844 });
    await page.getByRole('button', { name: '打开导航' }).click();
    await openSettings(page); await page.getByRole('tab', { name: '通用', exact: true }).click();
    await page.getByRole('radio', { name: '跟随系统', exact: true }).click();
    await expect(page.getByRole('radio', { name: '跟随系统', exact: true })).toBeChecked();
    await page.emulateMedia({ colorScheme: 'dark' }); await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark');
    await page.emulateMedia({ colorScheme: 'light' }); await expect(page.locator('html')).toHaveAttribute('data-theme', 'light');
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    await page.screenshot({ path: '.local-data/settings-mobile.png', fullPage: true });
    await page.getByRole('tab', { name: '账号与安全' }).click(); await page.getByLabel('当前密码', { exact: true }).focus();
    await page.keyboard.press('Shift+Tab'); await expect(page.getByRole('dialog', { name: '设置', exact: true })).toBeVisible();
});
test('Agent 凭据表单跨页保留，未复制的密钥关闭前有提示', async ({ page }) => {
    await openSettings(page); await page.getByRole('tab', { name: 'Agent 接入', exact: true }).click();
    await page.getByRole('button', { name: '创建凭据', exact: true }).click();
    await page.getByLabel('凭据名称').fill('Settings test Agent');
    await page.getByRole('checkbox', { name: /workspace.read/ }).check();
    await page.getByRole('tab', { name: '通用', exact: true }).click(); await page.getByRole('tab', { name: 'Agent 接入', exact: true }).click();
    await expect(page.getByLabel('凭据名称')).toHaveValue('Settings test Agent');
    await page.getByRole('button', { name: '生成凭据', exact: true }).click(); await expect(page.getByText('仅显示一次，请妥善保管')).toBeVisible();
    await page.getByRole('dialog', { name: '设置', exact: true }).getByRole('button', { name: '关闭', exact: true }).click();
    await expect(page.getByRole('dialog', { name: '关闭设置？' })).toContainText('密钥尚未复制');
});
