import { test, expect, type Page } from '@playwright/test';
const headers = { 'x-workbench-client':'test' };
async function login(page: Page) { expect((await page.request.post('/api/login',{headers,data:{username:'test-admin',password:'e2e-password-123'}})).ok()).toBe(true); await page.goto('/admin'); }
test('项目创建、重命名、成员加入移出、归档恢复与删除形成闭环',async({page})=>{
    await login(page); await page.getByRole('button',{name:'项目管理',exact:true}).click(); await page.getByRole('button',{name:'创建项目',exact:true}).click();
    await page.getByRole('dialog').getByLabel('项目名称').fill('生命周期验证项目');await page.getByRole('dialog').getByRole('button',{name:'确认',exact:true}).click();
    await expect(page.getByRole('heading',{name:'生命周期验证项目',exact:true,level:2})).toBeVisible();
    await page.getByRole('combobox',{name:'选择账号',exact:true}).selectOption({label:'designer'});await page.getByRole('checkbox',{name:'查看草稿与正式设计',exact:true}).check();await page.getByRole('button',{name:'加入此项目',exact:true}).click();await expect(page.getByRole('button',{name:'移出项目',exact:true})).toBeVisible();
    await page.getByRole('button',{name:'移出项目',exact:true}).click();const removal=page.getByRole('dialog');await removal.getByLabel('输入名称以确认').fill('designer');await removal.getByRole('button',{name:'移出项目',exact:true}).click();await expect(removal).toHaveCount(0);await expect(page.getByRole('button',{name:'加入此项目',exact:true})).toBeVisible();
    await page.getByRole('button',{name:'概览',exact:true}).click();await page.getByRole('button',{name:'重命名项目',exact:true}).click();await page.getByRole('dialog').getByLabel('项目名称').fill('重命名后的项目');await page.getByRole('dialog').getByRole('button',{name:'确认',exact:true}).click();await expect(page.getByRole('heading',{name:'重命名后的项目',exact:true})).toBeVisible();
    await page.screenshot({path:'.local-data/projects-desktop.png',fullPage:true});
    await page.getByRole('button',{name:'危险操作',exact:true}).click();await page.getByRole('button',{name:'查看删除影响'}).click();await expect(page.getByRole('dialog')).toContainText('请先归档项目');await page.getByRole('dialog').getByRole('button',{name:'取消',exact:true}).click();
    const changeState=async(name:string)=>{await page.getByRole('button',{name,exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'确认',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);};
    await changeState('归档项目');await expect(page.getByRole('button',{name:'恢复项目',exact:true})).toBeVisible();await changeState('恢复项目');await expect(page.getByRole('button',{name:'归档项目',exact:true})).toBeVisible();await changeState('归档项目');
    await page.setViewportSize({width:390,height:844});await page.emulateMedia({colorScheme:'dark'});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:'.local-data/projects-mobile.png',fullPage:true,animations:'disabled'});
    await page.getByRole('button',{name:'查看删除影响'}).click();await page.getByRole('dialog').getByLabel('输入名称以确认').fill('错误名称');await expect(page.getByRole('dialog').getByRole('button',{name:'删除项目',exact:true})).toBeDisabled();await page.getByRole('dialog').getByLabel('输入名称以确认').fill('重命名后的项目');await page.getByRole('dialog').getByRole('button',{name:'删除项目',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);await expect(page.getByRole('heading',{name:'重命名后的项目',exact:true})).toHaveCount(0);
});
test('账号危险操作显示自删保护，普通干净账号可删除且不影响其他账号',async({page})=>{
    await login(page);await page.getByRole('button',{name:'test-admin 平台管理员'}).click();await page.locator('.admin-more summary').click();await page.getByRole('button',{name:'删除账号',exact:true}).click();await expect(page.getByRole('dialog')).toContainText('不能删除当前登录账号');await expect(page.getByRole('dialog').getByRole('button',{name:'删除账号',exact:true})).toBeDisabled();await page.getByRole('dialog').getByRole('button',{name:'取消',exact:true}).click();
    await page.getByRole('button',{name:'创建账号',exact:true}).click();await page.getByRole('dialog').getByLabel('账号名称').fill('待删除账号');await page.getByRole('dialog').getByLabel('新密码（至少 10 个字符）').fill('management-password');await page.getByRole('dialog').getByRole('button',{name:'确认',exact:true}).click();await expect(page.getByRole('heading',{name:'待删除账号',exact:true})).toBeVisible();
    await page.locator('.admin-more summary').click();await page.getByRole('button',{name:'删除账号',exact:true}).click();await page.getByRole('dialog').getByLabel('输入名称以确认').fill('待删除账号');await page.screenshot({path:'.local-data/account-removal.png',fullPage:true});await page.getByRole('dialog').getByRole('button',{name:'删除账号',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);await expect(page.getByRole('region',{name:'账号列表'}).getByText('待删除账号',{exact:true})).toHaveCount(0);await expect(page.getByRole('button',{name:'test-admin 平台管理员'})).toBeVisible();
});
