

test('多负责人共享一条任务，筛选、取消分配与刷新保持一致', async ({ page }) => {
    await login(page); await openSchedule(page);
    await page.getByRole('button', { name: '新建任务', exact: true }).click();
    const dialog = page.getByRole('dialog');
    await dialog.getByLabel('任务标题', { exact: true }).fill('多人共同负责测试');
    await dialog.getByRole('checkbox', { name: 'designer', exact: true }).check();
    await dialog.getByRole('checkbox', { name: 'developer', exact: true }).check();
    await dialog.getByLabel('开始日期', { exact: true }).fill(localToday());
    await dialog.getByLabel('结束日期', { exact: true }).fill(localToday());
    await dialog.getByRole('button', { name: '保存任务', exact: true }).click();
    await expect(dialog).not.toBeVisible();
    const rows = page.locator('.schedule-task-open').filter({ hasText: '多人共同负责测试' });
    await expect(rows).toHaveCount(2);
    await page.getByRole('button', { name: '只看我的', exact: true }).click();
    await expect(rows).toHaveCount(1);
    await rows.click();
    await expect(dialog.getByRole('checkbox', { name: 'developer', exact: true })).toBeChecked();
    await dialog.getByRole('checkbox', { name: 'developer', exact: true }).uncheck();
    await dialog.getByRole('button', { name: '保存任务', exact: true }).click();
    await expect(dialog).not.toBeVisible();
    await page.reload(); await openSchedule(page);
    await expect(rows).toHaveCount(1);
    const snapshot = await (await page.request.get('/api/schedule', { headers })).json();
    const matches = snapshot.tasks.filter((task: any) => task.title === '多人共同负责测试');
    expect(matches).toHaveLength(1);
    expect(matches[0].ownerIds).toHaveLength(1);
});
import { test, expect, type Page } from '@playwright/test';
import { emptyTask, localToday, dateNumber, dateString } from '../../src/shared/schedule';
const headers = { 'x-workbench-client': 'test', 'x-project-id': 'demo' };
async function login(page: Page, username = 'designer') {
    expect((await page.request.post('/api/login', { headers, data: { username, password: 'e2e-password-123' } })).ok()).toBe(true);
    await page.goto('/');
}
async function openSchedule(page: Page) {
    await page.getByRole('navigation', { name: '项目共享', exact: true }).getByRole('button', { name: '任务排期', exact: true }).click();
    await expect(page.getByRole('heading', { name: '任务排期', exact: true })).toBeVisible();
}
test('统一父子任务支持账号分配、时间轴、范围筛选和持久化', async ({ page }) => {
    const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
    await login(page); await openSchedule(page);
    await page.getByRole('button', { name: '新建任务', exact: true }).click();
    let dialog = page.getByRole('dialog');
    await dialog.getByLabel('任务标题', { exact: true }).fill('排期测试 · 可玩原型');
    await dialog.getByRole('checkbox', { name: 'designer', exact: true }).check();
    await dialog.getByLabel('开始日期', { exact: true }).fill(localToday());
    await dialog.getByLabel('结束日期', { exact: true }).fill(dateString(dateNumber(localToday()) + 10));
    await dialog.getByLabel('完成标准', { exact: true }).fill('核心流程可用于内部试玩');
    await dialog.getByRole('button', { name: '保存任务', exact: true }).click();
    await expect(dialog).not.toBeVisible();
    await page.locator('.schedule-task-open').filter({ hasText: '排期测试 · 可玩原型' }).click();
    await page.getByRole('button', { name: '添加子任务', exact: true }).click();
    dialog = page.getByRole('dialog');
    await dialog.getByLabel('任务标题', { exact: true }).fill('排期测试 · 召唤回归');
    await dialog.getByRole('checkbox', { name: 'developer', exact: true }).check();
    await dialog.getByLabel('开始日期', { exact: true }).fill(localToday());
    await dialog.getByLabel('结束日期', { exact: true }).fill(dateString(dateNumber(localToday()) + 12));
    await expect(dialog.getByRole('status')).toContainText('超出上级排期');
    await dialog.getByRole('combobox', { name: '状态', exact: true }).selectOption('blocked');
    await dialog.getByLabel('阻塞原因', { exact: true }).fill('等待确认测试范围');
    await dialog.getByRole('button', { name: '保存任务', exact: true }).click();
    await expect(dialog).not.toBeVisible();
    await expect(page.locator('.schedule-task-open').filter({ hasText: '排期测试 · 召唤回归' })).toBeVisible();
    await page.getByRole('button', { name: '只看我的', exact: true }).click();
    await expect(page.locator('.schedule-task-open').filter({ hasText: '排期测试 · 召唤回归' })).toHaveCount(0);
    await page.getByRole('button', { name: '只看我的', exact: true }).click();
    await page.getByRole('button', { name: '任务树', exact: true }).click();
    const parentRow = page.locator('.schedule-row').filter({ has: page.locator('.schedule-task-open').filter({ hasText: '排期测试 · 可玩原型' }) });
    await parentRow.getByRole('button', { name: '收起子任务', exact: true }).click();
    await expect(page.locator('.schedule-task-open').filter({ hasText: '排期测试 · 召唤回归' })).toHaveCount(0);
    await parentRow.getByRole('button', { name: '展开子任务', exact: true }).click();
    const snapshot = await (await page.request.get('/api/schedule', { headers })).json();
    const parent = snapshot.tasks.find((task: any) => task.title === '排期测试 · 可玩原型');
    await page.getByRole('combobox', { name: '任务范围', exact: true }).selectOption(parent.id);
    await expect(page.locator('.schedule-task-open').filter({ hasText: '排期测试 · 召唤回归' })).toBeVisible();
    await page.getByRole('button', { name: '成员排期', exact: true }).click();
    await page.screenshot({ path: '.local-data/schedule-light.png', fullPage: true });
    await page.evaluate(() => document.documentElement.setAttribute('data-theme', 'dark'));
    await page.screenshot({ path: '.local-data/schedule-dark.png', fullPage: true, animations: 'disabled' });
    await page.locator('.schedule-task-open').filter({ hasText: '排期测试 · 召唤回归' }).click();
    await page.screenshot({ path: '.local-data/schedule-detail.png', fullPage: true });
    await page.getByRole('dialog').getByRole('combobox', { name: '父任务', exact: true }).selectOption('');
    await page.getByRole('button', { name: '保存任务', exact: true }).click();
    await expect(page.getByRole('dialog')).not.toBeVisible();
    await page.getByRole('combobox', { name: '任务范围', exact: true }).selectOption('');
    await page.reload();
    await expect(page.getByRole('heading', { name: '任务排期', exact: true })).toBeVisible();
    const reopened = await (await page.request.get('/api/schedule', { headers })).json();
    expect(reopened.tasks.find((task: any) => task.title === '排期测试 · 召唤回归').parentId).toBeNull();
    await page.setViewportSize({ width: 390, height: 844 });
    await expect(page.getByRole('button', { name: '新建任务', exact: true })).toBeVisible();
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    await page.screenshot({ path: '.local-data/schedule-mobile.png', fullPage: true });
    await page.getByRole('button', { name: '新建任务', exact: true }).click();
    await expect(page.getByRole('button', { name: '保存任务', exact: true })).toBeVisible();
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    expect(errors).toEqual([]);
});
test('并发冲突保留输入，不覆盖其他人的修改', async ({ page }) => {
    await login(page); const response = await page.request.post('/api/schedule/tasks', { headers, data: { requestId: crypto.randomUUID(), version: 0, task: { ...emptyTask, title: '排期测试 · 冲突保护' } } });
    expect(response.ok()).toBe(true); const original = await response.json(); await openSchedule(page);
    await page.locator('.schedule-backlog-list button').filter({ hasText: original.title }).click();
    await page.getByRole('dialog').getByLabel('任务标题', { exact: true }).fill('我的未保存输入');
    const { id, version, created, updated, ...fields } = original;
    expect((await page.request.post('/api/schedule/tasks', { headers, data: { requestId: crypto.randomUUID(), id, version, task: { ...fields, title: '其他人的修改' } } })).ok()).toBe(true);
    await page.getByRole('button', { name: '保存任务', exact: true }).click();
    await expect(page.getByRole('dialog').getByRole('alert')).toContainText('任务已被他人修改');
    await expect(page.getByRole('dialog').getByLabel('任务标题', { exact: true })).toHaveValue('我的未保存输入');
    const snapshot = await (await page.request.get('/api/schedule', { headers })).json();
    expect(snapshot.tasks.find((task: any) => task.id === id).title).toBe('其他人的修改');
    page.once('dialog', dialog => dialog.accept());
    await page.getByRole('dialog').getByRole('button', { name: '重新读取', exact: true }).click();
    await expect(page.getByRole('dialog').getByLabel('任务标题', { exact: true })).toHaveValue('其他人的修改');
    await page.getByRole('dialog').getByLabel('任务标题', { exact: true }).fill('我的未保存输入');
    await page.route('**/api/schedule', route => route.fulfill({ status: 403, contentType: 'application/json', body: JSON.stringify({ error: '缺少权限: schedule.read' }) }));
    await page.evaluate(() => window.dispatchEvent(new Event('focus')));
    await expect(page.locator('.schedule-page > .schedule-error')).toContainText('schedule.read');
    await expect(page.getByRole('dialog').getByLabel('任务标题', { exact: true })).toHaveValue('我的未保存输入');
    page.once('dialog', dialog => dialog.accept());
    await page.getByRole('dialog').getByRole('button', { name: '关闭', exact: true }).first().click();
    await expect(page.getByRole('dialog')).not.toBeVisible();
});
test('仅排期权限账号可独立访问，只能更新自己的任务', async ({ page }) => {
    await login(page, 'test-admin');
    const username = 'schedule-member-' + Date.now();
    const created = await page.request.post('/api/admin/users', { headers, data: { username, password: 'e2e-password-123' } }); expect(created.ok()).toBe(true); const userId = (await created.json()).id;
    expect((await page.request.post('/api/admin/member', { headers, data: { userId, projectId: 'demo', scopes: ['schedule.read', 'schedule.update'], expectedScopes: null } })).ok()).toBe(true);
    await login(page);
    expect((await page.request.post('/api/schedule/tasks', { headers, data: { requestId: crypto.randomUUID(), version: 0, task: { ...emptyTask, title: '排期测试 · 本人更新', ownerIds: [userId] } } })).ok()).toBe(true);
    await login(page, username);
    await expect(page.getByRole('heading', { name: '你已加入项目' })).toBeVisible();
    await page.getByRole('button', { name: '打开任务排期', exact: true }).click();
    await expect(page.getByRole('heading', { name: '任务排期', exact: true })).toBeVisible();
    await expect(page.getByRole('button', { name: '新建任务', exact: true })).toHaveCount(0);
    await expect(page.locator('.schedule-resize')).toHaveCount(0);
    await page.locator('.schedule-backlog-list button').filter({ hasText: '排期测试 · 本人更新' }).click();
    const dialog = page.getByRole('dialog');
    for (const checkbox of await dialog.getByRole('group', { name: '负责人', exact: true }).getByRole('checkbox').all()) await expect(checkbox).toBeDisabled();
    await expect(dialog.getByRole('combobox', { name: '父任务', exact: true })).toBeDisabled();
    await expect(dialog.getByLabel('任务标题', { exact: true })).toBeDisabled();
    await dialog.getByRole('combobox', { name: '状态', exact: true }).selectOption('doing');
    await dialog.getByRole('button', { name: '保存任务', exact: true }).click();
    await expect(dialog).not.toBeVisible();
    await expect(page.locator('.schedule-backlog-list button').filter({ hasText: '排期测试 · 本人更新' })).toContainText('进行中');
});
