import { describe, it, expect } from 'vitest';
import { diagnostics, entitySchema, type CollectionView, type Tree } from '../src/shared/model';
import { queryViewResult, matchesFilter, viewFilters } from '../src/shared/viewQuery';
const tree: Tree = { collection: { id: 'collection', kind: 'collection', title: '查询测试', path: 'collection.json', fields: [{ key: 'cost', label: '消耗', type: 'number', required: false }, { key: 'tags', label: '标签', type: 'multi', required: false }, { key: 'date', label: '日期', type: 'date', required: false }, { key: 'enabled', label: '启用', type: 'boolean', required: false }] } };
for (let index = 0; index < 35; index++) { const id = 'row-' + String(index).padStart(2, '0'); tree[id] = { id, kind: 'object', path: id + '.md', title: '记录 ' + index, body: '', collection: 'collection', fields: { cost: index, tags: [index % 2 ? '红' : '蓝', '共同'], date: '2026-09-' + String(index % 8 + 1).padStart(2, '0'), enabled: index % 2 === 0 } }; }
const view: CollectionView = { id: 'view', kind: 'view', title: '测试视图', path: 'view.json', collection: 'collection', layout: 'table', columns: ['title','cost','tags'], filter: null, sort: null };
describe('统一视图查询', () => {
    it('旧筛选不迁移也可查询，缺省不分页', () => { const legacy = { ...view, filter: { key: 'cost', value: '2' } }; expect(viewFilters(legacy)).toEqual([{ key: 'cost', operator: 'contains', value: '2' }]); expect(queryViewResult(tree, legacy).filteredCount).toBe(13); expect(queryViewResult(tree, view).rows).toHaveLength(35); });
    it('跨列 AND，同列多选 OR，筛选后排序再分页', () => { const result = queryViewResult(tree, { ...view, filters: [{ key: 'cost', operator: 'gte', value: 10 }, { key: 'tags', operator: 'in', value: ['红'] }], sort: { key: 'cost', descending: true }, pagination: { pageSize: 10 } }); expect(result.filteredCount).toBe(12); expect(result.rows).toHaveLength(10); expect(result.rows[0].fields.cost).toBe(33); expect(result.pageCount).toBe(2); });
    it('页面越界和负数收敛到有效页，排序相同按 ID 稳定排序', () => { const query = { ...view, pagination: { pageSize: 10 as const } }; expect(queryViewResult(tree, query, 100).page).toBe(4); expect(queryViewResult(tree, query, -2).page).toBe(1); expect(queryViewResult(tree, query, 4).rows).toHaveLength(5); });
    it('空多选表示零结果，空结果仍有可浏览第一页', () => { const result = queryViewResult(tree, { ...view, filters: [{ key: 'tags', operator: 'in', value: [] }], pagination: { pageSize: 10 } }); expect(result.rows).toHaveLength(0); expect(result.pageCount).toBe(1); });
    it('数值与字符串不混为相等，空值不作为零', () => { expect(matchesFilter('2', { key: 'cost', operator: 'equals', value: 2 })).toBe(false); expect(matchesFilter(null, { key: 'cost', operator: 'gte', value: 0 })).toBe(false); expect(matchesFilter([], { key: 'tags', operator: 'empty' })).toBe(true); });
    it('快速搜索包含可见字段，引用字段使用标题', () => { expect(queryViewResult(tree, { ...view, search: '共同' }).filteredCount).toBe(35); expect(queryViewResult(tree, { ...view, columns: ['title'], search: '共同' }).filteredCount).toBe(0); });
    it('数值范围含边界，日期范围与最近七天含当日', () => { const dateField = { key: 'date', label: '日期', type: 'date' as const, required: false }; expect(matchesFilter(2, { key: 'cost', operator: 'between', value: [2,3] })).toBe(true); expect(matchesFilter('2026-09-02', { key: 'date', operator: 'last7days' }, dateField, tree, new Date(2026,8,8))).toBe(true); expect(matchesFilter('2026-09-01', { key: 'date', operator: 'last7days' }, dateField, tree, new Date(2026,8,8))).toBe(false); });
    it('类型不兼容、反向区间与未知字段在写入前拒绝', () => { for (const filter of [{ key: 'missing', operator: 'equals', value: 'x' }, { key: 'cost', operator: 'between', value: [8,2] }, { key: 'cost', operator: 'equals', value: '2' }]) expect(diagnostics({ ...tree, view: { ...view, filters: [filter] } as CollectionView })).not.toHaveLength(0); });
    it('拒绝无界页大小，合法新旧格式均可读取', () => { expect(entitySchema.safeParse({ ...view, pagination: { pageSize: 999 } }).success).toBe(false); expect(entitySchema.safeParse(view).success).toBe(true); expect(entitySchema.safeParse({ ...view, filters: [], filterLogic: 'and', pagination: { pageSize: 25 } }).success).toBe(true); });
});

