import { randomUUID } from './uuid';
import { t } from './i18n';
import { useEffect, useState } from 'react';
import { BookOpen, CheckCircle2, Clock3, ChevronLeft, Search } from 'lucide-react';
import { api, notify, reload } from './state';
import { flushEditing, locked } from './editing';
import { Modal } from './Modal';
import { ReviewBrowser } from './ReviewBrowser';
const pendingLabel = '待同步至实现', confirmedLabel = '已确认同步至实现';
const synced = (change: any) => change.confirmations.some((record: any) => record.active);
const timestamp = (value: string) => new Date(value).toLocaleString();
export function Changes({ canSync }: { canSync: boolean }) {
    const [withdrawing, setWithdrawing] = useState<any>(null), [withdrawBusy, setWithdrawBusy] = useState(false), [withdrawError, setWithdrawError] = useState('');
    const [changes, setChanges] = useState<any[]>([]), [filter, setFilter] = useState('all'), [query, setQuery] = useState(''), [selected, setSelected] = useState('');
    const [batch, setBatch] = useState(false), [selection, setSelection] = useState<string[]>([]), [confirming, setConfirming] = useState<any[] | null>(null), [revoking, setRevoking] = useState<any>(null), [error, setError] = useState(''), [mobileDetail, setMobileDetail] = useState(false);
    const load = async () => { try { const next = await api('/changes'); setChanges(next); setSelection(current => current.filter(id => next.some((change: any) => change.id === id && !synced(change)))); setError(''); } catch (error: any) { setError(error.message); } };
    useEffect(() => { void load(); const listener = (event: Event) => { if (['publication', 'confirmation'].includes((event as CustomEvent).detail?.kind)) void load(); }; window.addEventListener('server-event', listener); return () => window.removeEventListener('server-event', listener); }, []);
    const filtered = changes.filter(change => (filter === 'all' || synced(change) === (filter === 'confirmed')) && (change.title + ' ' + change.description + ' ' + change.actor.username).toLowerCase().includes(query.trim().toLowerCase()));
    const current = filtered.find(change => change.id === selected) || filtered[0];
    const confirmation = current?.confirmations.find((record: any) => record.active);
    return <div className="release-history"><header className="release-heading"><BookOpen size={26}/><div><h1>{t("发布记录")}</h1><p>{t("查看已发布的正式设计，以及这些修改是否已同步到游戏实现。")}</p></div></header>
        <div className="release-flow"><span><BookOpen size={17}/>{t("发布后成为团队正式设计")}</span><span>→</span><span><Clock3 size={17}/>{t(pendingLabel)}</span><span>→</span><span><CheckCircle2 size={17}/>{t(confirmedLabel)}</span></div>
        <div className="release-filters"><div role="group" aria-label={t("按实现进度筛选")}>{[['all',t("全部")],['pending',pendingLabel],['confirmed',confirmedLabel]].map(([value, label]) => <button key={value} aria-pressed={filter === value} onClick={() => { setFilter(value); setMobileDetail(false); }}>{t(label)}<small>{changes.filter(change => value === 'all' || synced(change) === (value === 'confirmed')).length}</small></button>)}</div><label><Search size={16}/><input aria-label={t("搜索发布记录")} placeholder={t("标题、说明或发布人")} value={query} onChange={event => { setQuery(event.target.value); setMobileDetail(false); }}/></label>{canSync && <button onClick={() => { setBatch(!batch); setSelection([]); }}>{batch ? t("退出批量选择") : t("批量确认")}</button>}</div>
        {error && <p role="alert" className="error-list">{t(error)}<button onClick={() => void load()}>{t("重试")}</button></p>}
        {batch && canSync && <div className="release-batch"><span>{t("已选")} {selection.length}{t("条待同步记录（跨筛选保留）")}</span><button disabled={!selection.length} onClick={() => setConfirming(changes.filter(change => selection.includes(change.id)))}>{t("确认所选记录已同步至实现")}</button></div>}
        {!current ? <div className="release-empty"><BookOpen size={30}/><h2>{changes.length ? t("没有符合条件的发布记录") : t("还没有正式发布")}</h2><p>{changes.length ? t("试试其他状态或搜索词。") : t("草稿会自动保存。准备好后，使用“发布变更”将它更新为团队正式设计。")}</p></div> : <div className={'release-history-body' + (mobileDetail ? ' showing-detail' : '')}>
            <nav className="release-list" aria-label={t("发布记录列表")}>{filtered.map(change => <div key={change.id} className={'release-entry' + (current.id === change.id ? ' selected' : '')}>{batch && canSync && !synced(change) && <input type="checkbox" aria-label={t("选择 ") + change.title} checked={selection.includes(change.id)} onChange={event => setSelection(event.target.checked ? [...selection, change.id] : selection.filter(id => id !== change.id))}/>}<button aria-current={current.id === change.id ? 'true' : undefined} onClick={() => { setSelected(change.id); setMobileDetail(true); }}><strong>{change.title}</strong><small>{change.actor.username} · {timestamp(change.created)}</small><span>{new Set(change.diff.map((item: any) => item.id)).size}{t("份内容 ·")} {change.description || t("未填写说明")}</span><span className={'sync-badge ' + (synced(change) ? 'confirmed' : 'pending')}>{synced(change) ? <CheckCircle2 size={14}/> : <Clock3 size={14}/>}{synced(change) ? t(confirmedLabel) : t(pendingLabel)}</span></button></div>)}</nav>
            <article className="release-record change-card" aria-label={t("发布详情")}><button className="release-back" onClick={() => setMobileDetail(false)}><ChevronLeft size={16}/>{t("返回发布列表")}</button><header><div><small>{t("团队正式设计 ·")} {timestamp(current.created)}</small><h2>{current.title}</h2><p>{t("由")} {current.actor.username}{t("发布")}</p></div><span className={'sync-badge ' + (confirmation ? 'confirmed' : 'pending')}>{confirmation ? t(confirmedLabel) : t(pendingLabel)}</span></header><p className="release-note">{current.description || t("本次发布未填写说明。")}</p><h3>{t("本次修改")}</h3><ReviewBrowser key={current.id} items={current.review || []}/>
            <section className="implementation-record"><header><h3>{t("实现进度")}</h3>{canSync && !confirmation && <button className="primary" onClick={() => setConfirming([current])}>{t("确认已同步至实现")}</button>}</header>{confirmation ? <><p className="implementation-confirmed"><CheckCircle2 size={17}/>{t(confirmedLabel)}</p><p>{t("由")} {confirmation.actor.username}{t("确认 ·")} {timestamp(confirmation.created)}</p><p>{confirmation.note}</p>{canSync && <button onClick={() => setRevoking(current)}>{t("重新标记为待同步至实现")}</button>}</> : <><p><Clock3 size={16}/> {t(pendingLabel)}</p><p className="muted">{t("这份正式设计还没有实现同步确认；不代表它一定需要修改代码。")}</p>{current.confirmations[0] && <p>{t("最近记录：")}{current.confirmations[0].note} · {current.confirmations[0].actor.username}</p>}</>}</section>
            <details className="release-technical"><summary>{t("版本与实现记录")}</summary><p>{t("设计版本")} <code>{current.revision}</code></p>{current.confirmations.map((record: any) => <section key={record.id}><strong>{record.actor.username} · {timestamp(record.created)}</strong><p>{record.note}</p><p>{t("实现版本")} <code>{record.repository} @ {record.commit_id}</code></p></section>)}<small>{t("当前状态以“实现进度”为准；历史记录保留。")}</small></details></article>
        </div>}
        {current?.withdrawalBlocker === null && <button disabled={locked()} onClick={() => { setWithdrawError(''); setWithdrawing(current); }}>{t('撤回到草稿')}</button>}
        {withdrawing && <Modal title={t('撤回到草稿')} onClose={() => setWithdrawing(null)} busy={withdrawBusy}><h3>{withdrawing.title}</h3><p>{t('团队正式版本将回到上一版，本次发布记录将删除。内容恢复为你的草稿，保留名称和简介。')}</p>{withdrawError && <p role="alert">{t(withdrawError)}</p>}<button disabled={withdrawBusy} onClick={() => setWithdrawing(null)}>{t('取消')}</button><button className="danger" disabled={withdrawBusy || locked()} onClick={async () => { setWithdrawBusy(true); setWithdrawError(''); try { await flushEditing(); await api('/changes/withdraw', { id: withdrawing.id, revision: withdrawing.revision }); setWithdrawing(null); await reload(); await load(); notify(t('已撤回到草稿，名称和简介已保留')); } catch (error: any) { setWithdrawError(error.message); await load(); } finally { setWithdrawBusy(false); } }}>{t('确认撤回')}</button></Modal>}
        {confirming && <SyncDialog changes={confirming} onClose={() => setConfirming(null)} onDone={async () => { setConfirming(null); setSelection([]); await load(); }}/>} {revoking && <SyncDialog changes={[revoking]} revoke onClose={() => setRevoking(null)} onDone={async () => { setRevoking(null); await load(); }}/>} 
    </div>;
}
function SyncDialog({ changes, revoke = false, onClose, onDone }: { changes: any[]; revoke?: boolean; onClose: () => void; onDone: () => Promise<void> }) {
    const [busy, setBusy] = useState(false), [error, setError] = useState('');
    return <Modal title={revoke ? t("重新标记为待同步至实现") : t("确认已同步至实现")} className="sync-dialog" onClose={onClose} busy={busy}><p>{revoke ? t("保留已有确认记录，将以下发布重新列入待同步。") : t("确认这些正式设计与所填写的实现版本一致。现有实现已经满足、无需修改代码时，也可以确认。")}</p><ul>{changes.map(change => <li key={change.id}>{change.title}</li>)}</ul><form onSubmit={async event => {
        event.preventDefault(); const values = Object.fromEntries(new FormData(event.currentTarget)); const record = changes[0].confirmations.find((item: any) => item.active);
        setBusy(true); setError(''); try { await api('/changes/confirm', { requestId: randomUUID(), ids: changes.map(change => change.id), repository: revoke ? record.repository : values.repository, commit: revoke ? record.commit_id : values.commit, note: revoke ? '重新标记为待同步至实现：' + values.note : values.note, active: !revoke }); await onDone(); notify(revoke ? '已重新标记为待同步至实现' : '已确认同步至实现'); } catch (error: any) { setError(error.message); } finally { setBusy(false); }
    }}>{!revoke && <><label>{t("代码仓库标识")}<input name="repository" required disabled={busy} placeholder={t("实现所在仓库")}/></label><label>{t("实现版本（代码 commit）")}<input name="commit" required disabled={busy} placeholder={t("填写已检查的代码版本，不要求新建提交")}/></label></>}<label>{revoke ? t("重新标记的原因") : t("确认说明")}<textarea name="note" required disabled={busy} placeholder={revoke ? t("为什么需要重新核对实现？") : t("说明已修改并检查，或现有实现为什么已经满足。")}/></label>{error && <p className="error-list" role="alert">{t(error)}</p>}<small>{t("此状态由有权限的成员或 Agent 确认，平台不会自动检验代码。")}</small><footer><button className="primary" disabled={busy}>{busy ? t("保存中…") : revoke ? t("确认重新标记") : t("将 ") + changes.length + t(" 条记录确认为已同步至实现")}</button></footer></form></Modal>;
}
