import { t } from './i18n';
import { useEffect, useRef, useState, useId } from 'react';
import { createPortal } from 'react-dom';
import { Filter, X, ChevronLeft, ChevronRight } from 'lucide-react';
import type { CollectionView, Field, Tree } from '../shared/model';
import { displayValue, fieldValue, filterOperators, queryViewResult, viewFilters, type ViewFilter } from '../shared/viewQuery';
import { locked, flushEditing, registerBuffer, editingChanged } from './editing';
import { notify } from './state';
export const operatorLabels: Record<ViewFilter['operator'], string> = { contains: '包含', equals: '等于', startsWith: '开头是', empty: '为空', notEmpty: '不为空', gt: '大于 / 晚于', gte: '大于等于 / 不早于', lt: '小于 / 早于', lte: '小于等于 / 不晚于', between: '介于', in: '勾选值', today: '今天', last7days: '最近 7 天' };
export type ChangeView = (patch: Partial<CollectionView>) => Promise<void>;
export function ColumnFilter({ field, view, tree, change }: { field: Field; view: CollectionView; tree: Tree; change: ChangeView }) {
    const [open, setOpen] = useState(false);
    const anchor = useRef<HTMLButtonElement>(null);
    const active = viewFilters(view).find(filter => filter.key === field.key);
    const sorted = view.sort?.key === field.key;
    return <><button ref={anchor} className={'column-filter' + (active || sorted ? ' active' : '')} disabled={locked()} aria-label={t("筛选 ") + field.label} aria-haspopup="dialog" aria-expanded={open} title={t("筛选与排序：") + field.label} onClick={() => void flushEditing().then(() => setOpen(true)).catch(error => notify(error.message, true))}><span>{field.label}</span><Filter size={13}/>{sorted && <small>{view.sort!.descending ? '↓' : '↑'}</small>}</button>{open && <FilterPanel field={field} view={view} tree={tree} change={change} active={active} anchor={anchor.current} close={() => { setOpen(false); anchor.current?.focus(); }}/>}</>;
}
function FilterPanel({ field, view, tree, active, anchor, change, close }: { field: Field; view: CollectionView; tree: Tree; active?: ViewFilter; anchor: HTMLElement|null; change: ChangeView; close: () => void }) {
    const buffer = useId();
    const finished = useRef(false);
    const saving = useRef<Promise<void>|null>(null);
    useEffect(() => registerBuffer('filter-dialog:' + buffer, { dirty: () => !finished.current, flush: async () => { if (saving.current) await saving.current; else throw Error(t("请先应用或关闭列筛选")); } }), [buffer]);
    const [operator, setOperator] = useState<ViewFilter['operator']>(active?.operator || (filterOperators[field.type].includes('in') ? 'in' : 'equals'));
    const [value, setValue] = useState(String(Array.isArray(active?.value) ? active.value[0] ?? '' : active?.value ?? ''));
    const [end, setEnd] = useState(String(Array.isArray(active?.value) ? active.value[1] ?? '' : ''));
    const [checked, setChecked] = useState<(string|number|boolean)[]>(active?.operator === 'in' && Array.isArray(active.value) ? active.value : []);
    const [search, setSearch] = useState(''), [busy, setBusy] = useState(false), [error, setError] = useState('');
    const filters = viewFilters(view).filter(filter => filter.key !== field.key);
    const rows = queryViewResult(tree, { ...view, filters, filter: null, pagination: { pageSize: null } }).rows;
    const values = [...new Set([...field.options || [], ...rows.flatMap(row => { const value = fieldValue(row, field.key); return Array.isArray(value) ? value : value == null || value === '' ? [] : [value]; })] as (string|number|boolean)[])].sort((left, right) => displayValue(left, field, tree).localeCompare(displayValue(right, field, tree), 'zh-CN'));
    const options = values.filter(value => displayValue(value, field, tree).toLocaleLowerCase().includes(search.toLocaleLowerCase()));
    const box = anchor?.getBoundingClientRect();
    const inputType = field.type === 'number' ? 'number' : field.type === 'date' ? 'date' : 'text';
    const parsed = (text: string) => field.type === 'number' ? Number(text) : field.type === 'boolean' ? text === 'true' : text;
    const commit = async (patch: Partial<CollectionView>) => { setBusy(true); setError(''); saving.current = change(patch); try { await saving.current; finished.current = true; close(); } catch (error: any) { setError(error.message + (error.details ? '：' + JSON.stringify(error.details) : '')); } finally { saving.current = null; setBusy(false); editingChanged(); } };
    const apply = () => { const noValue = ['empty','notEmpty','today','last7days'].includes(operator); if (!noValue && operator !== 'in' && (!value || operator === 'between' && !end)) { setError('请填写完整筛选值'); return; } const filter: ViewFilter = { key: field.key, operator, ...noValue ? {} : { value: operator === 'in' ? checked : operator === 'between' ? [parsed(value), parsed(end)] : parsed(value) } }; void commit({ filter: null, filters: [...filters, filter], filterLogic: 'and' }); };
    useEffect(() => { const dismiss = () => close(); window.addEventListener('resize', dismiss); return () => window.removeEventListener('resize', dismiss); }, []);
    return createPortal(<div className="filter-overlay" onMouseDown={event => { if (event.target === event.currentTarget && !busy) close(); }}><section className="filter-popover" role="dialog" aria-modal="true" aria-label={t("筛选：") + field.label} style={{ left: Math.max(8, Math.min(box?.left || 8, window.innerWidth - 328)), top: Math.max(8, Math.min((box?.bottom || 30) + 6, window.innerHeight - 530)) }} onKeyDown={event => { if (event.key === 'Escape') { event.stopPropagation(); close(); } if (event.key === 'Tab') { const controls = [...event.currentTarget.querySelectorAll<HTMLElement>('button:not(:disabled), input:not(:disabled), select:not(:disabled)')]; if (event.shiftKey && document.activeElement === controls[0]) { event.preventDefault(); controls.at(-1)?.focus(); } else if (!event.shiftKey && document.activeElement === controls.at(-1)) { event.preventDefault(); controls[0]?.focus(); } } }}>
        <header><strong>{field.label}</strong><button aria-label={t("关闭列筛选")} onClick={close}><X size={15}/></button></header>
        <div className="filter-sort"><button disabled={locked() || busy} onClick={() => void commit({ sort: { key: field.key, descending: false } })}>{t("升序 ↑")}</button><button disabled={locked() || busy} onClick={() => void commit({ sort: { key: field.key, descending: true } })}>{t("降序 ↓")}</button>{view.sort?.key === field.key && <button disabled={locked() || busy} onClick={() => void commit({ sort: null })}>{t("取消排序")}</button>}</div>
        <label>{t("筛选方式")}<select autoFocus aria-label={t("筛选方式")} disabled={locked() || busy} value={operator} onChange={event => { setOperator(event.target.value as ViewFilter['operator']); setValue(''); setEnd(''); }}>{filterOperators[field.type].map(operator => <option key={operator} value={operator}>{t(operatorLabels[operator])}</option>)}{active && !filterOperators[field.type].includes(active.operator) && <option value={active.operator}>{t(operatorLabels[active.operator])}</option>}</select></label>
        {operator === 'in' ? <><input aria-label={t("搜索筛选值")} placeholder={t("搜索选项…")} value={search} onChange={event => setSearch(event.target.value)}/><div className="filter-selection"><button disabled={locked() || busy} onClick={() => setChecked(current => [...new Set([...current, ...options])])}>{t("全选搜索结果")}</button><button disabled={locked() || busy} onClick={() => setChecked([])}>{t("清空选择")}</button><small>{t("已选")} {checked.length}</small></div><div className="filter-options">{options.slice(0, 100).map(option => <label key={typeof option + ':' + option}><input type="checkbox" disabled={locked() || busy} checked={checked.includes(option)} onChange={event => setChecked(current => event.target.checked ? [...current, option] : current.filter(value => value !== option))}/>{displayValue(option, field, tree)}</label>)}{!options.length && <p className="empty">{t("没有可选值，可切换筛选方式")}</p>}{options.length > 100 && <small>{t("仅展示前 100 项，请搜索缩小范围")}</small>}</div></> : !['empty','notEmpty','today','last7days'].includes(operator) && (field.type === 'boolean' ? <select aria-label={t("筛选值")} disabled={locked() || busy} value={value} onChange={event => setValue(event.target.value)}><option value="">{t("请选择")}</option><option value="true">{t("是")}</option><option value="false">{t("否")}</option></select> : <div className="filter-range"><input aria-label={t("筛选值")} disabled={locked() || busy} type={inputType} value={value} onChange={event => setValue(event.target.value)}/>{operator === 'between' && <><span>{t("至")}</span><input aria-label={t("筛选结束值")} disabled={locked() || busy} type={inputType} value={end} onChange={event => setEnd(event.target.value)}/></>}</div>)}
        {error && <p role="alert" className="error">{t(error)}</p>}<footer><button disabled={locked() || busy} onClick={() => void commit({ filter: null, filters, filterLogic: 'and' })}>{t("清除此列")}</button><button className="primary" disabled={locked() || busy} onClick={apply}>{busy ? t("保存中…") : t("应用筛选")}</button></footer><small>{t("保存到此视图；所有嵌入同步更新，可撤销。")}</small>
    </section></div>, document.body);
}
export function FilterChips({ view, fields, tree, change }: { view: CollectionView; fields: Field[]; tree: Tree; change: ChangeView }) {
    const filters = viewFilters(view);
    return filters.length > 0 || view.search ? <div className="filter-chips" aria-label={t("当前筛选条件")}>{filters.map(filter => { const field = fields.find(field => field.key === filter.key); return <button key={filter.key} disabled={locked()} title={t("清除筛选 ") + (field?.label || filter.key)} onClick={() => void change({ filter: null, filters: filters.filter(item => item.key !== filter.key), filterLogic: 'and' }).catch(() => {})}>{field?.label || filter.key} · {t(operatorLabels[filter.operator])}{filter.value !== undefined && ' ' + displayValue(filter.value, field, tree)}<X size={12}/></button>; })}{view.search && <span>{t("搜索：")}{view.search}</span>}<button disabled={locked()} onClick={() => void change({ filter: null, filters: [], search: '', filterLogic: 'and' }).catch(() => {})}>{t("清除全部")}</button></div> : null;
}
export function ViewPagination({ result, view, change, go }: { result: ReturnType<typeof queryViewResult>; view: CollectionView; change: ChangeView; go: (page: number) => void }) {
    return <footer className="view-pagination"><span>{t("共")} {result.totalCount} {t("条 · 筛选后")} {result.filteredCount} {t("条")}</span><div className="spacer"/><label>{t("每页")}<select aria-label={t("每页条数")} disabled={locked()} value={view.pagination?.pageSize || 'all'} onChange={event => void change({ pagination: { pageSize: event.target.value === 'all' ? null : Number(event.target.value) as 10|25|50|100 } }).catch(() => {})}>{[10,25,50,100].map(size => <option key={size} value={size}>{size}</option>)}<option value="all">{t("全部")}</option></select></label><button aria-label={t("上一页")} disabled={result.page <= 1} onClick={() => go(result.page - 1)}><ChevronLeft size={15}/></button><span aria-label={t("分页状态")}>{t("第")} {result.page} / {result.pageCount}{t("页")}</span><button aria-label={t("下一页")} disabled={result.page >= result.pageCount} onClick={() => go(result.page + 1)}><ChevronRight size={15}/></button></footer>;
}
